overrides:
  brace-expansion: '^5.0.9'
  js-yaml: '^4.3.0'
  fast-uri: '^3.1.5'

minimumReleaseAge: 7200 # 5 days
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43800 # 1 month
minimumReleaseAgeExclude:
  - '@bart.sk-eshop/*'
  - '@bart.sk-ecommerce/*'
trustPolicyExclude:
  - '@bart.sk-eshop/*'
  - '@bart.sk-ecommerce/*'
